### ISSUE TITLE
Build failure because of crossbeam-epoch const_fn_trait_bound

### ISSUE THREAD

**Issue by jonathanbelolo** [paritytech/substrate-contracts-node#44]
Thx!

error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /Users/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.8/src/atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable

I'm using this toolchain:

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.61.0-nightly (3b348d932 2022-02-19)

**Comment by cmichi** [comment]
This has been answered by another user [here](https://substrate.stackexchange.com/a/1004/227):

>`rustup default nightly`, and then rerun. It's accessing nightly features. I can confirm that it builds using cargo 1.61.0-nightly (65c8266 2022-03-09) on linux.

I'm hence closing the issue, feel free to reopen if it's still an issue for you.
